pub mod audio;
pub mod capture;
pub mod database;
pub mod game_detection;
pub mod game_watcher;
pub mod gsi_config;
pub mod hotkeys;
pub mod integrations;
pub mod jobs;
pub mod library;
pub mod media;
pub mod models;
pub mod native_audio;
pub mod native_wgc;
pub mod recorder;
pub mod settings;
pub mod storage;
pub mod upload;

pub use models::{Clip, ClipSource, GameEvent, GameEventType, RecordingStatus, UploadProvider};
pub use recorder::{AutoClipPolicy, EventDebouncer, RecorderService, ReplayBuffer};
pub use settings::AppSettings;
